CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    provider_id BIGINT
);

CREATE TABLE IF NOT EXISTS rentable_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL,
    rental_mode VARCHAR(20) NOT NULL,
    base_price NUMERIC(10, 2) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    quantity_total INTEGER NOT NULL,
    CONSTRAINT uk_inventory_branch_item UNIQUE (branch_id, item_id)
);

CREATE TABLE IF NOT EXISTS inventory_holds (
    id VARCHAR(64) PRIMARY KEY,
    item_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    start_at TIMESTAMP(6) NOT NULL,
    end_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);
